version: 0.2

phases:
  build:
    commands:
    - echo Entered build phase
    
  post_build:
    commands:
      -echo Build completed successfully
      - mvn clean package
        
artifacts:
  files:
    -target/aws-codedeploy.jar
  discard-paths: yes        
        