version: 0.2

phases:
  build:
    commands:
    - echo Entered build phase
    
  post_build:
    commands:
      - mvn clean package
      - echo Build completed successfully
        
artifacts:
  files:
    - target/aws-codedeploy.jar
  discard-paths: yes        
        